name: 'blogit-bot'
description: 'Build blog with Git'
branding:
  icon: 'file-text'
  color: 'yellow'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
