import { css } from '@emotion/css'
import { useMemo } from 'react'
import Link from 'next/link'

export default function Footer() {
  const footers = useMemo(
    () =>
      process.env.NEXT_PUBLIC_FOOTER?.split(';').map((item) =>
        item.split(','),
      ) || [],
    [],
  )

  return (
    <footer
      className={css`
        user-select: none;
        display: flex;
        align-items: center;
        height: 64px;
        padding: 0 20px;
        border-top: 1px solid #e1e4e8;
        span {
          color: #586069;
          font-size: 12px;
        }
        a {
          color: #0366d6;
          text-decoration: none;
          font-size: 12px;
        }
        a + a {
          margin-left: 16px;
        }
        a:hover,
        a:focus {
          text-decoration: underline;
        }
      `}
    >
      <span>
        Generated by:&nbsp;
        <a
          href="https://github.com/renzholy/blogit"
          target="_blank"
          rel="noreferrer"
        >
          Blogit
        </a>
      </span>
      <span
        className={css`
          flex: 1;
        `}
      />
      {footers.map(([name, href]) =>
        href.startsWith('http') || href.startsWith('//') ? (
          <a key={name} href={href} target="_blank" rel="noreferrer">
            {name}
          </a>
        ) : (
          <Link key={name} href={href}>
            {name}
          </Link>
        ),
      )}
    </footer>
  )
}
