name: release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push to Registries
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.self
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mosaic-web:sha-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/mosaic-web:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
